

select TOP 10 * from customer_data;

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer_data
group by gender;



--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount
from customer_data
where discount_applied= 'yes' and purchase_amount >= (select AVG(purchase_amount) from customer_data);


-- Q3. Which are the top 5 products with the highest average review rating?
select TOP 5 
item_purchased,
ROUND(AVG(review_rating), 2) as avg_rating
from customer_data
group by item_purchased
order by avg_rating DESC;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,
ROUND(AVG(purchase_amount),2) as avg_purchased_amount
from customer_data
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select subscription_status,
count(customer_id) as total_customers,
Round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer_data
group by subscription_status
order by avg_spend,total_revenue desc;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select TOP 5 item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) as discount_rate
from customer_data
group by item_purchased
order by discount_rate desc;



--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as (
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
	ELSE 'Loyal'
	END as customer_segment
from customer_data
)
select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment


--Q8. What are the top 3 most purchased products within each category? 





--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?





--Q10. What is the revenue contribution of each age group? 